platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Gridstone/SpecRepo-iOS.git'

project 'MPOLKitDemo.xcodeproj'

target 'MPOLKitDemo' do
    pod 'MPOLKit', :path => '../'
end
