# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def the_dependencies
  pod 'CoreKit', :path => '../CoreKit', :inhibit_warnings => false

  pod 'lottie-ios', '~> 2.1.3'
  pod 'Cluster', '2.1.1'

end

target 'PatternKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PatternKit
  the_dependencies

  target 'PatternKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
