# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def the_dependencies
  pod 'Alamofire', '4.5.1'
  pod 'Unbox', '2.5.0'
  pod 'Wrap', '2.1.1'
  pod 'lottie-ios', '~> 2.1.3'
  pod 'PromiseKit', '~> 6.0'
  pod 'PromiseKit/CoreLocation'
  pod 'KeychainAccess', '~> 3.1.1'
  pod 'Cache', '~> 4.1.2'
end

target 'CoreKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreKit
  the_dependencies

  target 'CoreKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
