included:
  - MPOL/Classes
force_cast: warning
force_try:
  severity: warning
line_length:
  warning: 150
  error: 300
function_body_length:
  - 100 # warning
  - 200 # error
identifier_name:
  min_length: 2

