platform :ios, '11.2'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Gridstone/SpecRepo-iOS.git'

workspace 'MPOL'
project 'MPOL.xcodeproj', 'External-Debug' => :debug, 'Internal-Debug' => :debug

def all_kits
    pod 'CoreKit',         :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'SketchKit',       :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'PatternKit',      :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'PublicSafetyKit', :path => '../../mPolKit-iOS', :inhibit_warnings => false
end

def core_app_extension
    pod 'CoreKitAppExtension', :path => '../../mPolKit-iOS'
end

target 'MPOL' do
    project 'MPOL.xcodeproj'
    all_kits
    pod "HockeySDK", :configurations => ['internal-release', 'internal-debug', 'external-release', 'external-debug']
    pod "HyperioniOS", :configurations => ['Debug']
    pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionTextModel'
    pod 'VoiceSearchManager'
    pod 'VoiceSearchManager/VehicleRegistrationTransformer'

    target 'MPOLTests' do
      inherit! :search_paths
      # Pods for testing
    end
end

target 'APNS Extension' do
    project 'MPOL.xcodeproj'
    core_app_extension
    pod 'KeychainAccess'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
