platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Gridstone/SpecRepo-iOS.git'

workspace 'CAD'
project 'CAD.xcodeproj'

def all_kits
    pod 'CoreKit',         :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'SketchKit',       :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'PatternKit',      :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'PublicSafetyKit', :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'DemoAppKit',      :path => '../../mPolKit-iOS', :inhibit_warnings => false
    pod 'ClientKit',       :path => '../ClientKit', :inhibit_warnings => false
end

target 'CAD' do
    project 'CAD.xcodeproj'
    all_kits
    pod "HockeySDK", :configurations => ['release', 'external-release', 'external-debug']
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            # config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
