# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def the_dependencies
  pod 'CoreKit', :path => '..', :inhibit_warnings => false
end

target 'SketchKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SketchKit
  the_dependencies

  target 'SketchKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
